name: Intro to Githyb actions

# When this workflow run
on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.5.3
        - run: echo "Hello World!"

        - uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest
